-- Multi-tenant root. `guardrails_md` and `inbound_webhook_token` are
-- deliberate deviations from the reference app (see plan): guardrails is a
-- dedicated field so brand-safety rules never get diluted when `profile` is
-- regenerated by AI, and the webhook token is per-company instead of one
-- secret shared by every tenant.

create table public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  website_url text,
  profile text,
  guardrails_md text,
  favicon_url text,

  suggested_subreddits text[] not null default '{}',
  search_keywords text[] not null default '{}',

  posts_min_upvotes integer not null default 2,
  posts_fetch_frequency_hours integer not null default 24,
  posts_fetch_hour_utc smallint not null default 12
    check (posts_fetch_hour_utc between 0 and 23),
  posts_sort text not null default 'new'
    check (posts_sort in ('new', 'top', 'hot', 'relevance')),
  posts_max_per_run integer not null default 100
    check (posts_max_per_run between 10 and 200),
  posts_fetch_enabled boolean not null default false,
  posts_last_fetched_at timestamptz,
  posts_last_scheduled_run_at timestamptz,
  posts_last_error text,
  posts_last_error_at timestamptz,
  posts_retry_pending boolean not null default false,

  inbound_webhook_token uuid not null default gen_random_uuid(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger companies_set_updated_at
  before update on public.companies
  for each row execute function public.set_updated_at();

alter table public.companies enable row level security;

create policy "staff full access companies"
  on public.companies for all to authenticated
  using (public.is_staff(auth.uid()))
  with check (public.is_staff(auth.uid()));
